<!-- Generated by `bun run demos` from src/site/demos/accordion-item.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Accordion from '$lib/styles/sprout/Accordion.svelte';
	import AccordionItem from '$lib/styles/sprout/AccordionItem.svelte';
</script>

<Accordion class="w-full">
	<AccordionItem title="A single item" meta="01" open>
		Built on &lt;details&gt;, so it opens and closes without JavaScript.
	</AccordionItem>
</Accordion>
