<!-- Generated by `bun run demos` from src/site/demos/avatar-group.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Avatar from '$lib/styles/sprout/Avatar.svelte';
	import AvatarGroup from '$lib/styles/sprout/AvatarGroup.svelte';
</script>

<AvatarGroup>
	<Avatar name="Nadia Q" tone="brand" />
	<Avatar name="Rafi A" tone="accent" />
	<Avatar name="Sita M" tone="violet" />
	<Avatar name="Dwi P" tone="neutral" />
</AvatarGroup>
