<!-- Generated by `bun run demos` from src/site/demos/badge.variants.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Badge from '$lib/styles/sprout/Badge.svelte';
	import { TONES } from '$lib/core/tones.js';
</script>

{#snippet check()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="m3 8 3.2 3.2L13 4.4" stroke="currentColor" stroke-width="1.6" />
	</svg>
{/snippet}

{#snippet clock()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<circle cx="8" cy="8" r="6" stroke="currentColor" stroke-width="1.4" />
		<path d="M8 4.5V8l2.5 1.5" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet cross()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="m4 4 8 8M12 4l-8 8" stroke="currentColor" stroke-width="1.6" />
	</svg>
{/snippet}

<div class="flex w-full flex-col gap-6">
	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">variant</p>
		<div class="flex flex-wrap items-center gap-2">
			<Badge variant="soft">Soft</Badge>
			<Badge variant="solid">Solid</Badge>
			<Badge variant="outline">Outline</Badge>
		</div>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">size</p>
		<div class="flex flex-wrap items-center gap-2">
			<Badge size="sm">Small</Badge>
			<Badge size="md">Medium</Badge>
		</div>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">tone</p>
		<div class="flex flex-wrap items-center gap-2">
			{#each TONES as tone (tone)}
				<Badge {tone}>{tone}</Badge>
			{/each}
		</div>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">icon</p>
		<div class="flex flex-wrap items-center gap-2">
			<Badge icon={check} tone="success">Paid</Badge>
			<Badge icon={clock} tone="warning" variant="outline">Pending</Badge>
			<Badge icon={cross} tone="danger" variant="solid">Failed</Badge>
			<Badge icon={check} size="sm">Small</Badge>
		</div>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">dot</p>
		<div class="flex flex-wrap items-center gap-2">
			<Badge dot>Live</Badge>
			<Badge dot tone="warning" variant="outline">Queued</Badge>
			<Badge dot tone="danger" variant="solid">Failed</Badge>
		</div>
	</div>
</div>
