<!-- Generated by `bun run demos` from src/site/demos/badge.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Badge from '$lib/styles/sprout/Badge.svelte';
	import { TONES } from '$lib/core/tones.js';
</script>

<div class="flex flex-wrap items-center gap-2">
	{#each TONES as tone (tone)}
		<Badge {tone} dot>{tone}</Badge>
	{/each}
	<Badge variant="solid">Solid</Badge>
	<Badge variant="outline" tone="accent">Outline</Badge>
</div>
