<!-- Generated by `bun run demos` from src/site/demos/breadcrumb.variants.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Breadcrumb from '$lib/styles/sprout/Breadcrumb.svelte';
</script>

{#snippet home()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path
			d="M2 7 8 2l6 5v6a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V7Z"
			stroke="currentColor"
			stroke-width="1.4"
		/>
	</svg>
{/snippet}

{#snippet folder()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="M2 4h4l1.5 2H14v7H2V4Z" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet file()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="M4 2h5l3 3v9H4V2Z" stroke="currentColor" stroke-width="1.4" />
		<path d="M9 2v3h3" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

<div class="flex w-full flex-col gap-6">
	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">icon</p>
		<Breadcrumb
			items={[
				{ label: 'Home', href: '#', icon: home },
				{ label: 'Projects', href: '#', icon: folder },
				{ label: 'Brand book', icon: file }
			]}
		/>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">separator</p>
		<div class="flex flex-col gap-3">
			<Breadcrumb
				separator="›"
				items={[
					{ label: 'Home', href: '#', icon: home },
					{ label: 'Components', href: '#' },
					{ label: 'Breadcrumb' }
				]}
			/>
			<Breadcrumb
				separator="•"
				tone="accent"
				items={[{ label: 'Docs', href: '#' }, { label: 'Theming' }]}
			/>
		</div>
	</div>
</div>
