<!-- Generated by `bun run demos` from src/site/demos/breadcrumb.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Breadcrumb from '$lib/styles/sprout/Breadcrumb.svelte';
</script>

<Breadcrumb
	items={[
		{ label: 'Design system', href: '#' },
		{ label: 'Components', href: '#' },
		{ label: 'Badge' }
	]}
/>
