<!-- Generated by `bun run demos` from src/site/demos/button.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Button from '$lib/styles/sprout/Button.svelte';
</script>

<div class="flex flex-wrap items-center gap-3">
	<Button>Solid</Button>
	<Button variant="soft" tone="accent">Soft</Button>
	<Button variant="outline" tone="violet">Outline</Button>
	<Button variant="ghost" tone="neutral">Ghost</Button>
	<Button variant="link">Link →</Button>
	<Button loading>Saving</Button>
	<Button tone="danger" disabled>Disabled</Button>
</div>
