<!-- Generated by `bun run demos` from src/site/demos/card.variants.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Button from '$lib/styles/sprout/Button.svelte';
	import Card from '$lib/styles/sprout/Card.svelte';
</script>

{#snippet spark()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path
			d="M8 1.5 9.6 6l4.4 1.6L9.6 9.2 8 13.5 6.4 9.2 2 7.6 6.4 6 8 1.5Z"
			stroke="currentColor"
			stroke-width="1.3"
		/>
	</svg>
{/snippet}

{#snippet lock()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<rect x="3" y="7" width="10" height="7" stroke="currentColor" stroke-width="1.4" />
		<path d="M5.5 7V5a2.5 2.5 0 0 1 5 0v2" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet bolt()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="M9 1.5 4 9h3.5L7 14.5 12 7H8.5L9 1.5Z" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

<div class="flex w-full flex-col gap-6">
	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">icon</p>
		<div class="grid gap-4 sm:grid-cols-3">
			<Card icon={spark} eyebrow="Outline" title="Highlights" interactive>
				<p class="text-sm text-text-secondary">The icon sits above the title.</p>
			</Card>
			<Card variant="filled" icon={lock} title="Permissions">
				<p class="text-sm text-text-secondary">Alt surface, no eyebrow.</p>
			</Card>
			<Card variant="tinted" tone="accent" icon={bolt} eyebrow="Tinted" title="Automations">
				<p class="text-sm text-text-secondary">Tone light step.</p>
			</Card>
		</div>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">accent + footer</p>
		<div class="grid gap-4 sm:grid-cols-2">
			<Card accent tone="violet" icon={bolt} title="Nightly render">
				<p class="text-sm text-text-secondary">Runs at 02:00 in the studio timezone.</p>
				{#snippet footer()}
					<div class="flex items-center justify-between">
						<span class="font-mono text-xs text-text-muted">Last run 6h ago</span>
						<Button size="sm" variant="ghost">Run now</Button>
					</div>
				{/snippet}
			</Card>
			<Card interactive icon={spark} title="Custom header">
				{#snippet header()}
					<div class="flex items-center justify-between">
						<span class="font-heading text-lg">A header snippet</span>
						<Button size="sm" variant="outline">Edit</Button>
					</div>
				{/snippet}
				<p class="text-sm text-text-secondary">A header snippet wins over icon and title.</p>
			</Card>
		</div>
	</div>
</div>
