<!-- Generated by `bun run demos` from src/site/demos/checkbox-group.variants.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import CheckboxGroup from '$lib/styles/sprout/CheckboxGroup.svelte';

	let channels = $state(['email']);
	let addons = $state(['audit']);
</script>

{#snippet mail()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<rect x="2" y="3.5" width="12" height="9" stroke="currentColor" stroke-width="1.4" />
		<path d="m2 4.5 6 4 6-4" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet chat()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="M2.5 3h11v8h-6l-3 2.5V11h-2V3Z" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet bell()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="M4 11V7a4 4 0 0 1 8 0v4l1 1.5H3L4 11Z" stroke="currentColor" stroke-width="1.4" />
		<path d="M6.5 13.5a1.5 1.5 0 0 0 3 0" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

<div class="flex w-full flex-col gap-6">
	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">boxed + icon</p>
		<CheckboxGroup
			legend="Notify me by"
			bind:value={channels}
			boxed
			orientation="horizontal"
			options={[
				{ value: 'email', label: 'Email', description: 'A daily digest.', icon: mail },
				{ value: 'chat', label: 'Chat', description: 'Straight to Slack.', icon: chat },
				{ value: 'push', label: 'Push', description: 'On mobile only.', icon: bell }
			]}
		/>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">
			capped — two at most, the rest lock
		</p>
		<CheckboxGroup
			legend="Add-ons"
			max={2}
			hint="Two are included in the retainer."
			tone="accent"
			bind:value={addons}
			options={[
				{ value: 'audit', label: 'Brand audit' },
				{ value: 'motion', label: 'Motion pack' },
				{ value: 'copy', label: 'Copywriting' },
				{ value: 'photo', label: 'Photography' }
			]}
		/>
	</div>
</div>
