<!-- Generated by `bun run demos` from src/site/demos/confirm-dialog.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Button from '$lib/styles/sprout/Button.svelte';
	import ConfirmDialog from '$lib/styles/sprout/ConfirmDialog.svelte';

	let open = $state(false);
</script>

<Button tone="danger" variant="soft" onclick={() => (open = true)}>Delete project…</Button>

<ConfirmDialog
	bind:open
	title="Delete this project?"
	description="Everything in it goes too. This cannot be undone."
	confirmLabel="Delete"
	onconfirm={() => new Promise((r) => setTimeout(r, 900))}
/>
