<!-- Generated by `bun run demos` from src/site/demos/date-picker.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import DatePicker from '$lib/styles/sprout/DatePicker.svelte';

	let value = $state('2026-08-15');
</script>

<div class="w-full max-w-xs">
	<DatePicker bind:value />
</div>
