<!-- Generated by `bun run demos` from src/site/demos/field.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Field from '$lib/styles/sprout/Field.svelte';
	import Input from '$lib/styles/sprout/Input.svelte';
</script>

<div class="grid w-full gap-5 sm:grid-cols-2">
	<Field label="Full name" hint="Shown on the invoice." required for="d-name">
		<Input id="d-name" placeholder="Nadia Q." />
	</Field>
	<Field label="Work email" error="That address is already registered." for="d-mail">
		<Input id="d-mail" invalid placeholder="you@studio.com" />
	</Field>
</div>
