<!-- Generated by `bun run demos` from src/site/demos/file-input.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import FileInput from '$lib/styles/sprout/FileInput.svelte';

	let files = $state<File[]>([]);
</script>

<div class="w-full max-w-md">
	<FileInput bind:files accept="image/*,.pdf" maxSize={2 * 1024 * 1024} tone="accent" />
</div>
