<!-- Generated by `bun run demos` from src/site/demos/input.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Input from '$lib/styles/sprout/Input.svelte';

	let value = $state('');
</script>

<div class="flex w-full max-w-sm flex-col gap-3">
	<Input bind:value placeholder="you@studio.com" />
	<Input placeholder="50.000.000" tone="accent">
		{#snippet prefix()}<span class="font-mono text-xs">Rp</span>{/snippet}
	</Input>
	<Input invalid placeholder="Invalid" />
</div>
