<!-- Generated by `bun run demos` from src/site/demos/label.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Label from '$lib/styles/sprout/Label.svelte';
</script>

<Label required>Work email</Label>
