<!-- Generated by `bun run demos` from src/site/demos/logo-cloud.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import LogoCloud from '$lib/styles/sprout/LogoCloud.svelte';
</script>

<div class="w-full border border-hairline">
	<LogoCloud
		title="Trusted by"
		logos={[
			{ name: 'Sundara' },
			{ name: 'Nusantara' },
			{ name: 'Kelana' },
			{ name: 'NC Group' },
			{ name: 'Bahari' }
		]}
	/>
</div>
