<!-- Generated by `bun run demos` from src/site/demos/menu-item.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Button from '$lib/styles/sprout/Button.svelte';
	import Dropdown from '$lib/styles/sprout/Dropdown.svelte';
	import MenuItem from '$lib/styles/sprout/MenuItem.svelte';
</script>

<Dropdown>
	{#snippet trigger()}
		<Button variant="outline" tone="neutral">Menu</Button>
	{/snippet}
	<MenuItem shortcut="⌘C">Plain</MenuItem>
	<MenuItem selected>Selected</MenuItem>
	<MenuItem disabled>Disabled</MenuItem>
	<MenuItem tone="danger">Danger</MenuItem>
</Dropdown>
