<!-- Generated by `bun run demos` from src/site/demos/multi-select.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import MultiSelect from '$lib/styles/sprout/MultiSelect.svelte';

	let value = $state(['brand', 'motion']);
</script>

<div class="w-full max-w-sm">
	<MultiSelect
		bind:value
		max={4}
		tone="violet"
		options={[
			{ value: 'brand', label: 'Brand identity', group: 'Design' },
			{ value: 'ui', label: 'Product UI', group: 'Design' },
			{ value: 'motion', label: 'Motion', group: 'Design' },
			{ value: 'copy', label: 'Copywriting', group: 'Content' },
			{ value: 'dev', label: 'Front-end build', group: 'Build' }
		]}
	/>
</div>
