<!-- Generated by `bun run demos` from src/site/demos/number-input.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import NumberInput from '$lib/styles/sprout/NumberInput.svelte';

	let value = $state(3);
</script>

<NumberInput bind:value min={0} max={10} class="max-w-40" />
