<!-- Generated by `bun run demos` from src/site/demos/pagination.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Pagination from '$lib/styles/sprout/Pagination.svelte';

	let page = $state(3);
</script>

<Pagination bind:page total={12} />
