<!-- Generated by `bun run demos` from src/site/demos/password-input.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import PasswordInput from '$lib/styles/sprout/PasswordInput.svelte';

	let value = $state('nqm');
</script>

<div class="w-full max-w-sm">
	<PasswordInput bind:value strength />
</div>
