<!-- Generated by `bun run demos` from src/site/demos/radio-group.variants.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import RadioGroup from '$lib/styles/sprout/RadioGroup.svelte';

	let plan = $state('studio');
	let ship = $state('standard');
	let plain = $state('weekly');
</script>

{#snippet seat()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<circle cx="8" cy="5.5" r="2.6" stroke="currentColor" stroke-width="1.4" />
		<path d="M3 14c0-2.5 2.2-4 5-4s5 1.5 5 4" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet team()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<circle cx="6" cy="6" r="2.4" stroke="currentColor" stroke-width="1.4" />
		<path
			d="M2 13.5c0-2.2 1.8-3.5 4-3.5s4 1.3 4 3.5M11 5.2a2.2 2.2 0 0 1 0 4.1m1 4.2c0-1.5-.5-2.6-1.4-3.3"
			stroke="currentColor"
			stroke-width="1.4"
		/>
	</svg>
{/snippet}

{#snippet truck()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="M1.5 4h7v7h-7V4Zm7 2H11l2.5 2.5V11h-5" stroke="currentColor" stroke-width="1.4" />
		<circle cx="4.5" cy="12.5" r="1.2" stroke="currentColor" stroke-width="1.3" />
		<circle cx="11" cy="12.5" r="1.2" stroke="currentColor" stroke-width="1.3" />
	</svg>
{/snippet}

{#snippet bolt()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="M9 1.5 4 9h3.5L7 14.5 12 7H8.5L9 1.5Z" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

<div class="flex w-full flex-col gap-6">
	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">
			boxed + icon — the icon is drawn in boxed mode
		</p>
		<RadioGroup
			legend="Plan"
			bind:value={plan}
			boxed
			options={[
				{ value: 'studio', label: 'Studio', description: 'For one designer.', icon: seat },
				{ value: 'agency', label: 'Agency', description: 'Up to ten seats.', icon: team }
			]}
		/>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">horizontal + hint</p>
		<RadioGroup
			legend="Delivery"
			hint="Both arrive within the working week."
			orientation="horizontal"
			boxed
			tone="accent"
			bind:value={ship}
			options={[
				{ value: 'standard', label: 'Standard', description: '3–5 days.', icon: truck },
				{ value: 'express', label: 'Express', description: 'Next day.', icon: bolt }
			]}
		/>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">plain + error</p>
		<RadioGroup
			legend="Digest"
			required
			error="Pick one to continue."
			bind:value={plain}
			options={[
				{ value: 'weekly', label: 'Weekly' },
				{ value: 'daily', label: 'Daily' },
				{ value: 'never', label: 'Never', disabled: true }
			]}
		/>
	</div>
</div>
