<!-- Generated by `bun run demos` from src/site/demos/radio.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Radio from '$lib/styles/sprout/Radio.svelte';

	let group = $state('monthly');
</script>

<div class="flex flex-col gap-3">
	<Radio bind:group value="monthly" label="Monthly billing" />
	<Radio bind:group value="yearly" label="Yearly billing" description="Save 20%." tone="success" />
</div>
