<!-- Generated by `bun run demos` from src/site/demos/skeleton.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Skeleton from '$lib/styles/sprout/Skeleton.svelte';
</script>

<div class="flex w-full max-w-sm flex-col gap-4">
	<Skeleton variant="text" lines={3} />
	<Skeleton variant="circle" />
</div>
