<!-- Generated by `bun run demos` from src/site/demos/table.variants.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Badge from '$lib/styles/sprout/Badge.svelte';
	import Button from '$lib/styles/sprout/Button.svelte';
	import Input from '$lib/styles/sprout/Input.svelte';
	import Pagination from '$lib/styles/sprout/Pagination.svelte';
	import Select from '$lib/styles/sprout/Select.svelte';
	import Table from '$lib/styles/sprout/Table.svelte';

	const rows = [
		{ id: 'p1', project: 'Sundara', client: 'Sundara', status: 'Live', budget: 84 },
		{ id: 'p2', project: 'Nusantara', client: 'NC Group', status: 'In review', budget: 52 },
		{ id: 'p3', project: 'Kelana', client: 'Kelana', status: 'Draft', budget: 120 }
	];

	const columns = [
		{ key: 'project', label: 'Project', sortable: true },
		{ key: 'client', label: 'Client' },
		{ key: 'status', label: 'Status' },
		{ key: 'budget', label: 'Budget', sortable: true, align: 'right' as const, class: 'font-mono' }
	];

	const tones = { Live: 'success', 'In review': 'warning', Draft: 'neutral' } as const;

	let query = $state('');
	let filter = $state('all');
	let page = $state(1);
	let selected = $state<string[]>(['p1', 'p3']);
</script>

{#snippet status(row: (typeof rows)[number], value: unknown)}
	{#if row.status === value}
		<Badge tone={tones[row.status as keyof typeof tones]} size="sm">{row.status}</Badge>
	{/if}
{/snippet}

<div class="flex w-full flex-col gap-6">
	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">header</p>
		<Table {columns} {rows}>
			{#snippet header()}
				<div class="w-40">
					<Input bind:value={query} placeholder="Search…" />
				</div>
				<div class="w-32">
					<Select
						bind:value={filter}
						options={[
							{ value: 'all', label: 'All status' },
							{ value: 'live', label: 'Live' },
							{ value: 'review', label: 'In review' },
							{ value: 'draft', label: 'Draft' }
						]}
					/>
				</div>
				<div class="ml-auto flex items-center gap-2">
					<Button size="sm" variant="outline">Export</Button>
					<Button size="sm">New project</Button>
				</div>
			{/snippet}
			{#snippet cell({ row, column, value })}
				{#if column.key === 'status'}{@render status(row, value)}{:else}{value}{/if}
			{/snippet}
		</Table>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">footer</p>
		<Table {columns} {rows}>
			{#snippet cell({ row, column, value })}
				{#if column.key === 'status'}{@render status(row, value)}{:else}{value}{/if}
			{/snippet}
			{#snippet footer()}
				<span>Showing {rows.length} of 34 projects</span>
				<Pagination bind:page total={12} class="ml-auto" />
			{/snippet}
		</Table>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">
			bulk select — tick a row to swap the header for the bulk bar
		</p>
		<Table selectable bind:selected {columns} {rows}>
			{#snippet header()}
				<span class="font-heading text-base text-text">Projects</span>
			{/snippet}
			{#snippet bulkActions({ selected: keys, clear })}
				<Button size="sm" variant="ghost" onclick={clear}>Archive {keys.length}</Button>
				<Button size="sm" variant="soft" tone="danger">Delete</Button>
			{/snippet}
			{#snippet cell({ row, column, value })}
				{#if column.key === 'status'}{@render status(row, value)}{:else}{value}{/if}
			{/snippet}
		</Table>
	</div>
</div>
