<!-- Generated by `bun run demos` from src/site/demos/tags-input.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import TagsInput from '$lib/styles/sprout/TagsInput.svelte';

	let tags = $state(['svelte', 'tailwind']);
</script>

<div class="w-full max-w-sm">
	<TagsInput bind:tags max={6} placeholder="Add a topic, then Enter" tone="accent" />
</div>
