<!-- Generated by `bun run demos` from src/site/demos/tooltip.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in sprout. -->
<script lang="ts">
	import Button from '$lib/styles/sprout/Button.svelte';
	import Tooltip from '$lib/styles/sprout/Tooltip.svelte';
</script>

<div class="flex flex-wrap items-center gap-4">
	<Tooltip content="On top"><Button variant="outline" tone="neutral">Top</Button></Tooltip>
	<Tooltip content="On the right" placement="right"
		><Button variant="outline" tone="neutral">Right</Button></Tooltip
	>
</div>
