<!-- Generated by `bun run demos` from src/site/demos/avatar.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Avatar from '$lib/styles/paper/Avatar.svelte';
</script>

<div class="flex items-center gap-4">
	<Avatar name="Nadia Q" size="sm" />
	<Avatar name="Rafi A" tone="accent" />
	<Avatar name="Sita M" size="lg" tone="violet" squared />
</div>
