<!-- Generated by `bun run demos` from src/site/demos/avatar.variants.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Avatar from '$lib/styles/paper/Avatar.svelte';
	import AvatarGroup from '$lib/styles/paper/AvatarGroup.svelte';
</script>

{#snippet user()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<circle cx="8" cy="5.5" r="2.6" stroke="currentColor" stroke-width="1.4" />
		<path d="M3 14c0-2.5 2.2-4 5-4s5 1.5 5 4" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet robot()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<rect x="3" y="5" width="10" height="8" stroke="currentColor" stroke-width="1.4" />
		<path d="M8 2v3M6 8.5h.01M10 8.5h.01" stroke="currentColor" stroke-width="1.6" />
	</svg>
{/snippet}

<div class="flex w-full flex-col gap-6">
	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">
			fallback — an icon instead of initials
		</p>
		<div class="flex items-center gap-4">
			<Avatar fallback={user} />
			<Avatar fallback={user} tone="neutral" />
			<Avatar fallback={robot} tone="violet" squared />
			<Avatar name="Nadia Q" tone="accent" />
		</div>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">size</p>
		<div class="flex items-center gap-4">
			<Avatar fallback={user} size="xs" />
			<Avatar fallback={user} size="sm" />
			<Avatar fallback={user} size="md" />
			<Avatar fallback={user} size="lg" />
			<Avatar fallback={user} size="xl" />
		</div>
	</div>

	<div class="flex flex-col gap-2">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">in a group</p>
		<AvatarGroup>
			<Avatar name="Nadia Q" />
			<Avatar name="Rafi A" tone="accent" />
			<Avatar fallback={robot} tone="neutral" />
		</AvatarGroup>
	</div>
</div>
