<!-- Generated by `bun run demos` from src/site/demos/calendar.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Calendar from '$lib/styles/paper/Calendar.svelte';

	let value = $state('2026-08-15');
</script>

<div class="border border-hairline">
	<Calendar bind:value tone="accent" />
</div>
