<!-- Generated by `bun run demos` from src/site/demos/checkbox-group.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import CheckboxGroup from '$lib/styles/paper/CheckboxGroup.svelte';

	let value = $state(['wifi']);
</script>

<CheckboxGroup
	legend="Included"
	bind:value
	max={3}
	hint="Pick up to three."
	orientation="horizontal"
	boxed
	tone="accent"
	options={[
		{ value: 'wifi', label: 'Fibre wifi' },
		{ value: 'coffee', label: 'Barista coffee' },
		{ value: 'studio', label: 'Photo studio' },
		{ value: 'parking', label: 'Parking' }
	]}
/>
