<!-- Generated by `bun run demos` from src/site/demos/checkbox.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Checkbox from '$lib/styles/paper/Checkbox.svelte';

	let checked = $state(true);
</script>

<div class="flex flex-col gap-3">
	<Checkbox bind:checked label="I agree to the terms" description="Standard MSA." />
	<Checkbox indeterminate label="Partially selected" tone="violet" />
	<Checkbox label="Disabled" disabled />
</div>
