<!-- Generated by `bun run demos` from src/site/demos/combobox.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Combobox from '$lib/styles/paper/Combobox.svelte';

	let value = $state('');
</script>

<div class="w-full max-w-xs">
	<Combobox
		bind:value
		options={[
			{ value: 'jkt', label: 'Jakarta' },
			{ value: 'bdg', label: 'Bandung' },
			{ value: 'sby', label: 'Surabaya' },
			{ value: 'dps', label: 'Denpasar' }
		]}
	/>
</div>
