<!-- Generated by `bun run demos` from src/site/demos/divider.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Divider from '$lib/styles/paper/Divider.svelte';
</script>

<div class="flex w-full max-w-sm flex-col gap-4">
	<Divider />
	<Divider label="or" />
</div>
