<!-- Generated by `bun run demos` from src/site/demos/drawer.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Button from '$lib/styles/paper/Button.svelte';
	import Drawer from '$lib/styles/paper/Drawer.svelte';

	let open = $state(false);
</script>

<Button variant="outline" tone="neutral" onclick={() => (open = true)}>Open drawer</Button>

<Drawer bind:open side="right" title="Project settings">
	<p class="text-sm text-text-secondary">Slides in on the native dialog top layer.</p>
</Drawer>
