<!-- Generated by `bun run demos` from src/site/demos/dropdown.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Button from '$lib/styles/paper/Button.svelte';
	import Dropdown from '$lib/styles/paper/Dropdown.svelte';
	import MenuItem from '$lib/styles/paper/MenuItem.svelte';
	import MenuSeparator from '$lib/styles/paper/MenuSeparator.svelte';
</script>

<Dropdown>
	{#snippet trigger()}
		<Button variant="outline" tone="neutral">Actions</Button>
	{/snippet}
	<MenuSeparator label="Project" />
	<MenuItem shortcut="⌘C">Copy</MenuItem>
	<MenuItem shortcut="⌘D">Duplicate</MenuItem>
	<MenuSeparator />
	<MenuItem tone="danger">Delete</MenuItem>
</Dropdown>
