<!-- Generated by `bun run demos` from src/site/demos/dropzone.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Dropzone from '$lib/styles/paper/Dropzone.svelte';
</script>

<div class="w-full max-w-md">
	<Dropzone accept="image/*,.pdf" maxSize={5 * 1024 * 1024} maxFiles={4} tone="accent" />
</div>
