<!-- Generated by `bun run demos` from src/site/demos/empty-state.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Button from '$lib/styles/paper/Button.svelte';
	import EmptyState from '$lib/styles/paper/EmptyState.svelte';
</script>

<EmptyState
	title="No projects yet"
	description="Create your first project to see it here."
	tone="brand"
>
	{#snippet action()}
		<Button size="sm">New project</Button>
	{/snippet}
</EmptyState>
