<!-- Generated by `bun run demos` from src/site/demos/input-group.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Button from '$lib/styles/paper/Button.svelte';
	import Input from '$lib/styles/paper/Input.svelte';
	import InputGroup from '$lib/styles/paper/InputGroup.svelte';

	let value = $state('');
</script>

<InputGroup class="max-w-sm">
	<Input bind:value placeholder="you@studio.com" />
	<Button>Subscribe</Button>
</InputGroup>
