<!-- Generated by `bun run demos` from src/site/demos/input-addon.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Input from '$lib/styles/paper/Input.svelte';
	import InputAddon from '$lib/styles/paper/InputAddon.svelte';
	import InputGroup from '$lib/styles/paper/InputGroup.svelte';

	let handle = $state('');
	let weight = $state('');
</script>

<div class="flex w-full max-w-sm flex-col gap-3">
	<InputGroup>
		<InputAddon>https://</InputAddon>
		<Input bind:value={handle} placeholder="studio" />
		<InputAddon>.com</InputAddon>
	</InputGroup>

	<InputGroup>
		<Input bind:value={weight} placeholder="0" inputmode="decimal" />
		<InputAddon>kg</InputAddon>
	</InputGroup>
</div>
