<!-- Generated by `bun run demos` from src/site/demos/kbd.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Kbd from '$lib/styles/paper/Kbd.svelte';
</script>

<p class="font-sans text-sm text-text-secondary">Press <Kbd>⌘</Kbd> <Kbd>K</Kbd> to search</p>
