<!-- Generated by `bun run demos` from src/site/demos/link.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Link from '$lib/styles/paper/Link.svelte';
</script>

<div class="flex flex-wrap items-center gap-5">
	<Link href="#">Default</Link>
	<Link href="#" tone="accent" underline="always">Accent</Link>
	<Link href="https://nqmcreative.com" external>External</Link>
</div>
