<!-- Generated by `bun run demos` from src/site/demos/menu-separator.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Button from '$lib/styles/paper/Button.svelte';
	import Dropdown from '$lib/styles/paper/Dropdown.svelte';
	import MenuItem from '$lib/styles/paper/MenuItem.svelte';
	import MenuSeparator from '$lib/styles/paper/MenuSeparator.svelte';
</script>

<Dropdown>
	{#snippet trigger()}
		<Button variant="outline" tone="neutral">Menu</Button>
	{/snippet}
	<MenuSeparator label="Group" />
	<MenuItem>First</MenuItem>
	<MenuSeparator />
	<MenuItem>Second</MenuItem>
</Dropdown>
