<!-- Generated by `bun run demos` from src/site/demos/navbar.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Navbar from '$lib/styles/paper/Navbar.svelte';
	import ThemeToggle from '$lib/styles/paper/ThemeToggle.svelte';
</script>

<div class="w-full border border-hairline">
	<Navbar
		bordered={false}
		items={[
			{ label: 'Overview', href: '#', active: true },
			{ label: 'Projects', href: '#', badge: 12 },
			{
				label: 'Resources',
				items: [
					{ label: 'Brand kit', href: '#' },
					{ label: 'Templates', href: '#' }
				]
			}
		]}
	>
		{#snippet brand()}
			<span class="font-heading text-base font-medium tracking-tight"
				>nqm<span class="text-brand">.</span></span
			>
		{/snippet}
		{#snippet actions()}
			<ThemeToggle />
		{/snippet}
	</Navbar>
</div>
