<!-- Generated by `bun run demos` from src/site/demos/progress.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Progress from '$lib/styles/paper/Progress.svelte';
</script>

<div class="flex w-full max-w-sm flex-col gap-5">
	<Progress value={72} label="Storage" showValue />
	<Progress value={38} label="Queue" tone="accent" size="lg" showValue />
</div>
