<!-- Generated by `bun run demos` from src/site/demos/radio-group.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import RadioGroup from '$lib/styles/paper/RadioGroup.svelte';

	let value = $state('studio');
</script>

<RadioGroup
	legend="Plan"
	bind:value
	boxed
	options={[
		{ value: 'studio', label: 'Studio', description: 'For one designer.' },
		{ value: 'agency', label: 'Agency', description: 'Up to ten seats.' }
	]}
/>
