<!-- Generated by `bun run demos` from src/site/demos/search-input.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import SearchInput from '$lib/styles/paper/SearchInput.svelte';

	const cities = ['Yogyakarta', 'Bandung', 'Surabaya', 'Makassar', 'Medan'];

	let value = $state('');
	let query = $state('');

	const matches = $derived(
		cities.filter((city) => city.toLowerCase().includes(query.toLowerCase()))
	);
</script>

<div class="flex w-full max-w-sm flex-col gap-3">
	<SearchInput
		bind:value
		debounce={300}
		onsearch={(next) => (query = next)}
		placeholder="Search cities"
	/>
	<ul class="flex flex-col gap-1 font-sans text-sm text-text-secondary">
		{#each matches as city (city)}
			<li>{city}</li>
		{:else}
			<li class="text-text-muted">No matches</li>
		{/each}
	</ul>
</div>
