<!-- Generated by `bun run demos` from src/site/demos/segmented-control.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import SegmentedControl from '$lib/styles/paper/SegmentedControl.svelte';

	let value = $state('grid');
</script>

<SegmentedControl
	bind:value
	label="View"
	options={[
		{ value: 'grid', label: 'Grid' },
		{ value: 'list', label: 'List' },
		{ value: 'board', label: 'Board' },
		{ value: 'gantt', label: 'Gantt', disabled: true }
	]}
/>
