<!-- Generated by `bun run demos` from src/site/demos/select.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Select from '$lib/styles/paper/Select.svelte';

	let value = $state('studio');
</script>

<Select
	bind:value
	class="max-w-xs"
	options={[
		{ value: 'studio', label: 'Studio' },
		{ value: 'agency', label: 'Agency' },
		{ value: 'custom', label: 'Custom', disabled: true }
	]}
/>
