<!-- Generated by `bun run demos` from src/site/demos/slider.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Slider from '$lib/styles/paper/Slider.svelte';

	let value = $state(40);
</script>

<div class="w-full max-w-sm">
	<Slider bind:value label="Budget" showValue tone="accent" />
</div>
