<!-- Generated by `bun run demos` from src/site/demos/spinner.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Spinner from '$lib/styles/paper/Spinner.svelte';
</script>

<div class="flex items-center gap-6">
	<Spinner size="sm" tone="brand" />
	<Spinner size="md" tone="accent" />
	<Spinner size="lg" tone="violet" />
</div>
