<!-- Generated by `bun run demos` from src/site/demos/stats-band.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import StatsBand from '$lib/styles/paper/StatsBand.svelte';
</script>

<div class="w-full border border-hairline">
	<StatsBand
		title="Where the work went."
		class="py-10"
		stats={[
			{ label: 'Projects shipped', value: '48', delta: '12', trend: 'up', tone: 'brand' },
			{ label: 'Average sprint', value: '9 days', hint: 'Kick-off to review' },
			{ label: 'Retained clients', value: '82%', delta: '4%', trend: 'up', tone: 'success' }
		]}
	/>
</div>
