<!-- Generated by `bun run demos` from src/site/demos/steps.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Steps from '$lib/styles/paper/Steps.svelte';

	let current = $state(1);
</script>

<div class="flex w-full flex-col gap-8">
	<Steps
		bind:current
		clickable
		items={[
			{ label: 'Sign the SOW', description: 'Countersigned' },
			{ label: 'Kick-off call', description: 'Scheduled' },
			{ label: 'Brand audit' },
			{ label: 'First sprint' }
		]}
	/>
</div>
