<!-- Generated by `bun run demos` from src/site/demos/steps.variants.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Steps from '$lib/styles/paper/Steps.svelte';

	let iconed = $state(1);
	let vertical = $state(2);
</script>

{#snippet pen()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path d="M11 2.5 13.5 5 6 12.5 3 13l.5-3L11 2.5Z" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet call()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path
			d="M3 3h3l1 3-2 1a7 7 0 0 0 4 4l1-2 3 1v3H12A9 9 0 0 1 3 4V3Z"
			stroke="currentColor"
			stroke-width="1.4"
		/>
	</svg>
{/snippet}

{#snippet search()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<circle cx="7" cy="7" r="4.2" stroke="currentColor" stroke-width="1.4" />
		<path d="m10.2 10.2 3 3" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

{#snippet rocket()}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
		<path
			d="M8 1.5c2.5 1.5 3.5 4 3.5 6L8 11 4.5 7.5c0-2 1-4.5 3.5-6Z"
			stroke="currentColor"
			stroke-width="1.4"
		/>
		<path d="M6 11.5 4.5 14M10 11.5 11.5 14" stroke="currentColor" stroke-width="1.4" />
	</svg>
{/snippet}

<div class="flex w-full flex-col gap-8">
	<div class="flex flex-col gap-3">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">
			icon — replaces the number, a finished step keeps its check
		</p>
		<Steps
			bind:current={iconed}
			clickable
			items={[
				{ label: 'Sign the SOW', description: 'Countersigned', icon: pen },
				{ label: 'Kick-off call', description: 'Scheduled', icon: call },
				{ label: 'Brand audit', icon: search },
				{ label: 'First sprint', icon: rocket }
			]}
		/>
	</div>

	<div class="flex flex-col gap-3">
		<p class="font-mono text-[10px] tracking-wide text-text-muted uppercase">vertical + error</p>
		<Steps
			orientation="vertical"
			bind:current={vertical}
			items={[
				{ label: 'Upload assets', icon: pen },
				{ label: 'Licence check', description: 'Two fonts are unlicensed.', error: true },
				{ label: 'Publish', icon: rocket }
			]}
		/>
	</div>
</div>
