<!-- Generated by `bun run demos` from src/site/demos/switch.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Switch from '$lib/styles/paper/Switch.svelte';

	let checked = $state(true);
</script>

<Switch bind:checked label="Email notifications" description="Weekly digest only." tone="info" />
