<!-- Generated by `bun run demos` from src/site/demos/textarea.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Textarea from '$lib/styles/paper/Textarea.svelte';

	let value = $state('');
</script>

<Textarea bind:value placeholder="Tell us about the project…" class="max-w-sm" />
