<!-- Generated by `bun run demos` from src/site/demos/theme-toggle.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import ThemeToggle from '$lib/styles/paper/ThemeToggle.svelte';
</script>

<div class="flex flex-wrap items-center gap-5">
	<ThemeToggle />
	<ThemeToggle variant="segmented" />
</div>
