<!-- Generated by `bun run demos` from src/site/demos/toaster.svelte — do not edit. -->
<!-- Authored against matte; only the import path differs in paper. -->
<script lang="ts">
	import Button from '$lib/styles/paper/Button.svelte';
	import { toast } from '$lib/core/toast.svelte.js';
</script>

<div class="flex flex-wrap gap-3">
	<Button size="sm" onclick={() => toast.success('Saved')}>Success</Button>
	<Button size="sm" variant="soft" tone="danger" onclick={() => toast.error('Upload failed')}
		>Error</Button
	>
	<Button size="sm" variant="soft" tone="info" onclick={() => toast.info('Rendering started')}
		>Info</Button
	>
</div>
<p class="mt-3 font-sans text-sm text-text-muted">
	Toaster is already mounted in this site’s layout.
</p>
