/**
 * Copies each demo into every style it was not authored in, rewriting the one
 * line that differs: the import path.
 *
 * A demo is written once, against `DEMO_STYLE`. Every style implements the same
 * catalogue with the same props, so the copy is a path substitution and nothing
 * more — which is exactly the claim the parity suite enforces. Generating them
 * keeps the docs honest: the preview really does mount that style's component,
 * not the same one repainted.
 *
 * Run with `--check` to fail instead of writing.
 */
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { DEMO_STYLE, STYLES } from './catalogue.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv.includes('--check');

const sourceDir = new URL('src/site/demos/', `file://${root}`);
const demos = (await readdir(sourceDir)).filter((f) => f.endsWith('.svelte')).sort();

const header = (style, slug) =>
	`<!-- Generated by \`bun run demos\` from src/site/demos/${slug} — do not edit. -->\n` +
	`<!-- Authored against ${DEMO_STYLE}; only the import path differs in ${style}. -->\n`;

let stale = 0;

for (const style of STYLES) {
	if (style.name === DEMO_STYLE) continue;

	const outDir = new URL(`src/site/demos-${style.name}/`, `file://${root}`);
	if (!check) await mkdir(outDir, { recursive: true });

	const written = new Set();

	for (const slug of demos) {
		const source = await readFile(new URL(slug, sourceDir), 'utf8');
		const next =
			header(style.name, slug) +
			source.replaceAll(`$lib/styles/${DEMO_STYLE}/`, `$lib/styles/${style.name}/`);

		written.add(slug);
		const path = new URL(slug, outDir);

		let current = '';
		try {
			current = await readFile(path, 'utf8');
		} catch {
			/* new demo */
		}
		if (current === next) continue;

		stale++;
		if (check) {
			console.error(`src/site/demos-${style.name}/${slug} is stale — run \`bun run demos\``);
			continue;
		}
		await writeFile(path, next);
	}

	// A demo deleted upstream must not linger here.
	let existing = [];
	try {
		existing = (await readdir(outDir)).filter((f) => f.endsWith('.svelte'));
	} catch {
		/* not generated yet */
	}
	for (const orphan of existing.filter((f) => !written.has(f))) {
		stale++;
		if (check) {
			console.error(`src/site/demos-${style.name}/${orphan} has no source — run \`bun run demos\``);
			continue;
		}
		await rm(new URL(orphan, outDir));
	}
}

if (check && stale) process.exit(1);

const others = STYLES.length - 1;
console.log(
	stale
		? `demos written (${demos.length} × ${others} style${others === 1 ? '' : 's'})`
		: `demos up to date (${demos.length} × ${others} style${others === 1 ? '' : 's'})`
);
