/**
 * Writes each style's `index.ts`.
 *
 * The barrel is generated rather than hand-kept because there is one per
 * style: with three styles a new component would otherwise mean three barrels
 * to remember, and the one you forget is the one someone needs. Types are read
 * straight out of each `.svelte` file, so a new `export type` shows up without
 * being listed anywhere.
 *
 * Run with `--check` to fail instead of writing — `bun run lint` does.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { COMPONENTS, STYLES, CATEGORIES } from './catalogue.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv.includes('--check');

/** What every style re-exports from core, so one import covers the style. */
const CORE_VALUES = [
	'TONES',
	'focusRing',
	'peerFocusRing',
	'toneBorder',
	'toneBorderLeft',
	'toneBorderSoft',
	'toneFill',
	'toneFocusBorder',
	'toneFocusWithinBorder',
	'toneHoverBorder',
	'toneHoverText',
	'tonePeerChecked',
	'tonePeerFocus',
	'toneRing',
	'toneSoft',
	'toneSoftHover',
	'toneSolid',
	'toneSolidHover',
	'toneSurface',
	'toneText',
	'anchored',
	'clickOutside',
	'focusTrap',
	'focusable',
	'navigateList',
	'portal',
	'toast',
	'locale',
	'setLocale',
	'provideLocale',
	'useLocale',
	'enUS',
	'idID',
	'LocaleStore',
	'applyTheme',
	'storedTheme',
	'toISO',
	'fromISO',
	'today',
	'isSameDay',
	'addDays',
	'addMonths',
	'monthGrid',
	'weekdayNames',
	'monthLabel',
	'isOutOfRange',
	'formatISO',
	'parseFormatted'
];

const CORE_TYPES = [
	'Tone',
	'Placement',
	'AnchorOptions',
	'ClickOutsideOptions',
	'FocusTrapOptions',
	'Toast',
	'ToastOptions',
	'ToastAction',
	'Locale',
	'Theme',
	'DateFormat',
	'TableSort',
	'SortDirection',
	'RejectedFile'
];

/**
 * Types a component declares itself. Deliberately ignores `export … from`,
 * which is how a component re-surfaces a core type — the barrel already has
 * those, and exporting them twice is an error.
 */
function localTypes(source) {
	const names = [];
	for (const match of source.matchAll(
		/^\s*export\s+(?:type|interface)\s+([A-Za-z][\w]*)\s*[=<{]/gm
	))
		names.push(match[1]);
	return [...new Set(names)];
}

function block(names, keyword) {
	if (names.length === 0) return '';
	const kw = keyword ? ` ${keyword}` : '';
	const line = `export${kw} { ${names.join(', ')} } from '../../core/index.js';`;
	if (line.length <= 100) return line + '\n';
	return `export${kw} {\n\t${names.join(',\n\t')}\n} from '../../core/index.js';\n`;
}

async function build(style) {
	const dir = new URL(`src/lib/styles/${style.name}/`, `file://${root}`);
	const files = new Set(
		(await readdir(dir)).filter((f) => f.endsWith('.svelte')).map((f) => f.replace('.svelte', ''))
	);

	const missing = COMPONENTS.filter((c) => !files.has(c.name)).map((c) => c.name);
	if (missing.length) {
		console.error(`${style.name} is missing ${missing.length} component(s): ${missing.join(', ')}`);
		process.exitCode = 1;
		return null;
	}

	/** Components this style adds beyond the shared catalogue. */
	const extra = [...files].filter((f) => !COMPONENTS.some((c) => c.name === f)).sort();

	let out = `/**\n * ${style.title} — ${style.description}\n *\n`;
	out += ` * Generated by \`bun run index\`. Behaviour comes from\n`;
	out += ` * \`@nqmcreative/ui/core\`, re-exported below so this one import covers\n`;
	out += ` * the whole style.\n */\n\n`;

	out += `/* --- shared behaviour --- */\n`;
	out += block(CORE_VALUES, '');
	out += block(CORE_TYPES, 'type');

	for (const category of CATEGORIES) {
		const items = COMPONENTS.filter((c) => c.category === category);
		if (items.length === 0) continue;
		out += `\n/* --- ${category} --- */\n`;
		for (const item of items) {
			const source = await readFile(new URL(`${item.name}.svelte`, dir), 'utf8');
			out += `export { default as ${item.name} } from './${item.name}.svelte';\n`;
			const types = localTypes(source);
			if (types.length)
				out += `export type { ${types.join(', ')} } from './${item.name}.svelte';\n`;
		}
	}

	if (extra.length) {
		out += `\n/* --- ${style.name} only --- */\n`;
		for (const name of extra) {
			const source = await readFile(new URL(`${name}.svelte`, dir), 'utf8');
			out += `export { default as ${name} } from './${name}.svelte';\n`;
			const types = localTypes(source);
			if (types.length) out += `export type { ${types.join(', ')} } from './${name}.svelte';\n`;
		}
	}

	return out;
}

let stale = 0;
for (const style of STYLES) {
	const next = await build(style);
	if (next === null) continue;

	const path = new URL(`src/lib/styles/${style.name}/index.ts`, `file://${root}`);
	let current = '';
	try {
		current = await readFile(path, 'utf8');
	} catch {
		/* first run */
	}
	if (current === next) continue;

	stale++;
	if (check) {
		console.error(`src/lib/styles/${style.name}/index.ts is stale — run \`bun run index\``);
		process.exitCode = 1;
		continue;
	}
	await writeFile(path, next);
	console.log(`wrote src/lib/styles/${style.name}/index.ts`);
}

if (stale === 0 && !process.exitCode) console.log(`style barrels up to date (${STYLES.length})`);
