/**
 * Paper — The neutral one. Start here if unsure: soft corners, light shadows, generous spacing, and nothing that fights the content.
 *
 * Generated by `bun run index`. Behaviour comes from
 * `@nqmcreative/ui/core`, re-exported below so this one import covers
 * the whole style.
 */

/* --- shared behaviour --- */
export {
	TONES,
	focusRing,
	peerFocusRing,
	toneBorder,
	toneBorderLeft,
	toneBorderSoft,
	toneFill,
	toneFocusBorder,
	toneFocusWithinBorder,
	toneHoverBorder,
	toneHoverText,
	tonePeerChecked,
	tonePeerFocus,
	toneRing,
	toneSoft,
	toneSoftHover,
	toneSolid,
	toneSolidHover,
	toneSurface,
	toneText,
	anchored,
	clickOutside,
	focusTrap,
	focusable,
	navigateList,
	portal,
	toast,
	locale,
	setLocale,
	provideLocale,
	useLocale,
	enUS,
	idID,
	LocaleStore,
	applyTheme,
	storedTheme,
	toISO,
	fromISO,
	today,
	isSameDay,
	addDays,
	addMonths,
	monthGrid,
	weekdayNames,
	monthLabel,
	isOutOfRange,
	formatISO,
	parseFormatted
} from '../../core/index.js';
export type {
	Tone,
	Placement,
	AnchorOptions,
	ClickOutsideOptions,
	FocusTrapOptions,
	Toast,
	ToastOptions,
	ToastAction,
	Locale,
	Theme,
	DateFormat,
	TableSort,
	SortDirection,
	RejectedFile
} from '../../core/index.js';

/* --- locale --- */
export { default as LocaleProvider } from './LocaleProvider.svelte';

/* --- actions --- */
export { default as Button } from './Button.svelte';
export type { ButtonVariant, ButtonSize } from './Button.svelte';
export { default as Link } from './Link.svelte';

/* --- forms --- */
export { default as Input } from './Input.svelte';
export type { InputSize } from './Input.svelte';
export { default as Textarea } from './Textarea.svelte';
export { default as Select } from './Select.svelte';
export type { SelectOption } from './Select.svelte';
export { default as Checkbox } from './Checkbox.svelte';
export { default as Radio } from './Radio.svelte';
export { default as Switch } from './Switch.svelte';
export type { SwitchSize } from './Switch.svelte';
export { default as Field } from './Field.svelte';
export { default as Label } from './Label.svelte';
export { default as PasswordInput } from './PasswordInput.svelte';
export { default as NumberInput } from './NumberInput.svelte';
export { default as Slider } from './Slider.svelte';
export { default as RadioGroup } from './RadioGroup.svelte';
export type { RadioOption } from './RadioGroup.svelte';
export { default as CheckboxGroup } from './CheckboxGroup.svelte';
export type { CheckboxOption } from './CheckboxGroup.svelte';
export { default as SegmentedControl } from './SegmentedControl.svelte';
export type { SegmentOption, SegmentedSize } from './SegmentedControl.svelte';
export { default as InputGroup } from './InputGroup.svelte';
export { default as Combobox } from './Combobox.svelte';
export type { ComboboxOption } from './Combobox.svelte';
export { default as MultiSelect } from './MultiSelect.svelte';
export type { MultiSelectOption } from './MultiSelect.svelte';
export { default as DatePicker } from './DatePicker.svelte';
export { default as Calendar } from './Calendar.svelte';
export { default as Dropzone } from './Dropzone.svelte';

/* --- data display --- */
export { default as Badge } from './Badge.svelte';
export type { BadgeVariant, BadgeSize } from './Badge.svelte';
export { default as Avatar } from './Avatar.svelte';
export type { AvatarSize } from './Avatar.svelte';
export { default as AvatarGroup } from './AvatarGroup.svelte';
export { default as Card } from './Card.svelte';
export type { CardVariant } from './Card.svelte';
export { default as Stat } from './Stat.svelte';
export type { StatTrend } from './Stat.svelte';
export { default as Table } from './Table.svelte';
export type { TableColumn } from './Table.svelte';
export { default as Kbd } from './Kbd.svelte';

/* --- feedback --- */
export { default as Alert } from './Alert.svelte';
export type { AlertVariant } from './Alert.svelte';
export { default as Progress } from './Progress.svelte';
export type { ProgressSize } from './Progress.svelte';
export { default as Spinner } from './Spinner.svelte';
export type { SpinnerSize } from './Spinner.svelte';
export { default as Skeleton } from './Skeleton.svelte';
export type { SkeletonVariant } from './Skeleton.svelte';
export { default as EmptyState } from './EmptyState.svelte';
export { default as Toaster } from './Toaster.svelte';
export type { ToasterPosition } from './Toaster.svelte';

/* --- layout & navigation --- */
export { default as Divider } from './Divider.svelte';
export type { DividerOrientation } from './Divider.svelte';
export { default as Tabs } from './Tabs.svelte';
export type { TabItem, TabsVariant } from './Tabs.svelte';
export { default as Accordion } from './Accordion.svelte';
export { default as AccordionItem } from './AccordionItem.svelte';
export { default as Breadcrumb } from './Breadcrumb.svelte';
export type { BreadcrumbItem } from './Breadcrumb.svelte';
export { default as Pagination } from './Pagination.svelte';
export { default as Steps } from './Steps.svelte';
export type { StepItem } from './Steps.svelte';

/* --- app shell --- */
export { default as Navbar } from './Navbar.svelte';
export type { NavItem } from './Navbar.svelte';
export { default as Sidebar } from './Sidebar.svelte';
export type { SidebarItem, SidebarSection } from './Sidebar.svelte';
export { default as Footer } from './Footer.svelte';
export type { FooterLink, FooterColumn } from './Footer.svelte';

/* --- marketing --- */
export { default as HeroSection } from './HeroSection.svelte';
export { default as FeatureGrid } from './FeatureGrid.svelte';
export type { FeatureColumns } from './FeatureGrid.svelte';
export { default as FeatureCard } from './FeatureCard.svelte';
export { default as PricingCard } from './PricingCard.svelte';
export { default as Testimonial } from './Testimonial.svelte';
export type { TestimonialVariant } from './Testimonial.svelte';
export { default as LogoCloud } from './LogoCloud.svelte';
export type { Logo } from './LogoCloud.svelte';
export { default as CTASection } from './CTASection.svelte';
export type { CTAVariant } from './CTASection.svelte';
export { default as StatsBand } from './StatsBand.svelte';
export type { BandStat } from './StatsBand.svelte';

/* --- overlay --- */
export { default as Modal } from './Modal.svelte';
export type { ModalSize } from './Modal.svelte';
export { default as Drawer } from './Drawer.svelte';
export type { DrawerSide, DrawerSize } from './Drawer.svelte';
export { default as ConfirmDialog } from './ConfirmDialog.svelte';
export { default as CommandPalette } from './CommandPalette.svelte';
export type { CommandItem } from './CommandPalette.svelte';
export { default as ContextMenu } from './ContextMenu.svelte';
export { default as Dropdown } from './Dropdown.svelte';
export { default as MenuItem } from './MenuItem.svelte';
export { default as MenuSeparator } from './MenuSeparator.svelte';
export { default as Popover } from './Popover.svelte';
export { default as ThemeToggle } from './ThemeToggle.svelte';
export { default as Tooltip } from './Tooltip.svelte';
export type { TooltipPlacement } from './Tooltip.svelte';
